7. Личный проект: шаблонизируй это
htmlacademy-ecmascript/997865-cinemaddict-12 pull request #4
Opened 2020-09-13 10:03 UTC by KirillErz

2020-09-14 21:36 UTC, rubenovdev requested changes

2020-09-14 21:36 UTC, rubenovdev commented on src/mock/film.js
> +    "film_info": {
В этом проекте именуем переменные в стиле `camelCase`, в этом примере должно быть `filmInfo`
На 8 лекции данные будем получать с сервера (стиле `snake_case`), но для удобной работы мы будем адаптировать их под свой формат (`camelCase`)

2020-09-14 21:36 UTC, rubenovdev commented on src/view/film-card.js
> +  const {id, comments, film_info: {...film}, user_details: {...user}} = movie || {};
Неверно используемая деструктуризация , рекомендую статью learn.javascript.ru/destructuring-assignment
Станет понятно в чем ошибка

2020-09-14 21:36 UTC, rubenovdev commented on src/view/film-detail.js
> +  const valuesToString =  (...rest) => {
Для чего эта функция ?

2020-09-14 21:36 UTC, rubenovdev commented on src/view/menu.js
> +  switch (type) {
Можно сократить функцию и сразу возвращать значение из кейсов, пример:
```
switch (type) {
  case `all`:
      return `All movies`;
  case `watchlist`:
      return `Watchlist`;
...
}
```

2020-09-14 21:36 UTC, rubenovdev commented on src/view/user.js
> +    switch (true) {
Так же можно сразу возвращать значение

2020-09-14 21:36 UTC, rubenovdev commented on src/view/film-detail.js
> +  const {id, comments, film_info: {...film}, user_details: {...user}} = movie || {};
Неверно используемая деструктуризация

2020-09-15 18:35 UTC, KirillErz commented on src/mock/film.js
> +    "film_info": {
Я просто так и подумал, что с сервера будут snake_case и решил оставить

2020-09-16 21:37 UTC, rubenovdev requested changes
Не рендерятся карточки фильмов в разделах "Top rated" и "Most commented"

2020-09-16 21:37 UTC, rubenovdev commented on src/main.js
> +const countOfdisplayedMovie = 5;
Названия констант (постоянных значений) написаны прописными (заглавными) буквами, [пункт Б5](https://up.htmlacademy.ru/ecmascript/12/criteries#b5)

2020-09-16 21:37 UTC, rubenovdev commented on src/main.js
> +const UserProperties = generateRatingUser();
UserProperties не перечисление, т.к. содержит только одно свойство

2020-09-16 21:37 UTC, rubenovdev commented on src/main.js
> +  let constWillBeRendered = 0;
Необычное название переменной constWillBeRendered )

2020-09-17 11:23 UTC, rubenovdev approved these changes

2020-09-17 11:23 UTC, merged